module.exports = {
  dev: [
    'underscore',
    'webpack',
    'webpack-stream',
    'requirejs',
    'gulp',
    'gulp-eslint',
    'gulp-exclude-gitignore',
    'eslint',
    'eslint-config-xo',
    'eslint-config-xo-space',
    'karma',
    'karma-mocha',
    'karma-mocha-reporter',
    'karma-coverage',
    'karma-webpack',
    'karma-sourcemap-loader',
    'karma-phantomjs-launcher',
    'karma-chrome-launcher',
    'phantomjs-prebuilt',
    'mocha',
    'chai',
    'istanbul-instrumenter-loader',
  ],
};
